import sqlite3

from PyQt5 import QtCore, QtGui, QtWidgets


class NewWindowUI(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 300)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.text1 = QtWidgets.QLabel(self.centralwidget)
        self.text1.setGeometry(QtCore.QRect(10, 10, 100, 20))
        self.input1 = QtWidgets.QLineEdit(self.centralwidget)
        self.input1.setGeometry(QtCore.QRect(110, 10, 100, 20))
        self.text2 = QtWidgets.QLabel(self.centralwidget)
        self.text2.setGeometry(QtCore.QRect(10, 40, 100, 20))
        self.input2 = QtWidgets.QLineEdit(self.centralwidget)
        self.input2.setGeometry(QtCore.QRect(110, 40, 100, 20))
        self.text3 = QtWidgets.QLabel(self.centralwidget)
        self.text3.setGeometry(QtCore.QRect(10, 70, 100, 20))
        self.input3 = QtWidgets.QLineEdit(self.centralwidget)
        self.input3.setGeometry(QtCore.QRect(110, 70, 100, 20))
        self.text4 = QtWidgets.QLabel(self.centralwidget)
        self.text4.setGeometry(QtCore.QRect(10, 100, 100, 20))
        self.input4 = QtWidgets.QLineEdit(self.centralwidget)
        self.input4.setGeometry(QtCore.QRect(110, 100, 100, 20))
        self.text5 = QtWidgets.QLabel(self.centralwidget)
        self.text5.setGeometry(QtCore.QRect(10, 130, 100, 20))
        self.input5 = QtWidgets.QLineEdit(self.centralwidget)
        self.input5.setGeometry(QtCore.QRect(110, 130, 100, 20))
        self.text6 = QtWidgets.QLabel(self.centralwidget)
        self.text6.setGeometry(QtCore.QRect(10, 160, 100, 20))
        self.input6 = QtWidgets.QLineEdit(self.centralwidget)
        self.input6.setGeometry(QtCore.QRect(110, 160, 100, 20))
        self.pushbutton = QtWidgets.QPushButton(self.centralwidget)
        self.pushbutton.setGeometry(QtCore.QRect(150, 180, 100, 20))
        self.pushbutton.clicked.connect(self.save_info)
        self.error_label = QtWidgets.QLabel(self.centralwidget)
        self.error_label.setGeometry(QtCore.QRect(10, 180, 200, 30))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 554, 28))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.text1.setText(_translate("MainWindow", "Название сорта"))
        self.text2.setText(_translate("MainWindow", "Степнь обжарки"))
        self.text3.setText(_translate("MainWindow", "Молотый/в зернах"))
        self.text4.setText(_translate("MainWindow", "Описание вкуса"))
        self.text5.setText(_translate("MainWindow", "Цена"))
        self.text6.setText(_translate("MainWindow", "Объём упаковки, гр"))
        self.pushbutton.setText(_translate("MainWindow", "Добавить"))
        self.error_label.setText(_translate("MainWindow", ""))


class NewWindow2UI(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 300)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.text1 = QtWidgets.QLabel(self.centralwidget)
        self.text1.setGeometry(QtCore.QRect(10, 10, 100, 20))
        self.input1 = QtWidgets.QLineEdit(self.centralwidget)
        self.input1.setGeometry(QtCore.QRect(110, 10, 100, 20))
        self.text2 = QtWidgets.QLabel(self.centralwidget)
        self.text2.setGeometry(QtCore.QRect(10, 40, 100, 20))
        self.input2 = QtWidgets.QLineEdit(self.centralwidget)
        self.input2.setGeometry(QtCore.QRect(110, 40, 100, 20))
        self.text3 = QtWidgets.QLabel(self.centralwidget)
        self.text3.setGeometry(QtCore.QRect(10, 70, 100, 20))
        self.input3 = QtWidgets.QLineEdit(self.centralwidget)
        self.input3.setGeometry(QtCore.QRect(110, 70, 100, 20))
        self.text4 = QtWidgets.QLabel(self.centralwidget)
        self.text4.setGeometry(QtCore.QRect(10, 100, 100, 20))
        self.input4 = QtWidgets.QLineEdit(self.centralwidget)
        self.input4.setGeometry(QtCore.QRect(110, 100, 100, 20))
        self.text5 = QtWidgets.QLabel(self.centralwidget)
        self.text5.setGeometry(QtCore.QRect(10, 130, 100, 20))
        self.input5 = QtWidgets.QLineEdit(self.centralwidget)
        self.input5.setGeometry(QtCore.QRect(110, 130, 100, 20))
        self.text6 = QtWidgets.QLabel(self.centralwidget)
        self.text6.setGeometry(QtCore.QRect(10, 160, 100, 20))
        self.input6 = QtWidgets.QLineEdit(self.centralwidget)
        self.input6.setGeometry(QtCore.QRect(110, 160, 100, 20))
        self.pushbutton = QtWidgets.QPushButton(self.centralwidget)
        self.pushbutton.setGeometry(QtCore.QRect(150, 180, 100, 20))
        self.pushbutton.clicked.connect(self.save_info)
        self.error_label = QtWidgets.QLabel(self.centralwidget)
        self.error_label.setGeometry(QtCore.QRect(10, 180, 200, 30))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 554, 28))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.text1.setText(_translate("MainWindow", "Название сорта"))
        self.text2.setText(_translate("MainWindow", "Степнь обжарки"))
        self.text3.setText(_translate("MainWindow", "Молотый/в зернах"))
        self.text4.setText(_translate("MainWindow", "Описание вкуса"))
        self.text5.setText(_translate("MainWindow", "Цена"))
        self.text6.setText(_translate("MainWindow", "Объём упаковки, гр"))
        self.pushbutton.setText(_translate("MainWindow", "Добавить"))
        self.error_label.setText(_translate("MainWindow", ""))